---
name: CI
on:
  push:
    branches:
      - '**'
jobs:
  main:
    name: Ruby ${{ matrix.ruby }} using ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - jruby
        gemfile:
          - rails4.2
          - rails5.0
          - rails5.1
          - rails5.2
    steps:
      - uses: zendesk/checkout@v2
      - name: Remove gem-lockfiles for JRuby
        if: ${{ matrix.ruby == 'jruby' }}
        run: rm -v gemfiles/*.lock
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
